-- 프로그래머스 131533번. 상품 별 오프라인 매출 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131533

SELECT A.PRODUCT_CODE, A.PRICE * B.SALES_AMOUNT AS SALES_AMOUNT
FROM PRODUCT A
JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES_AMOUNT DESC, PRODUCT_CODE ASC;
