-- 프로그래머스 273710번. ROOT 아이템 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/273710

SELECT ITEM_ID, ITEM_NAME
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NULL
)
ORDER BY ITEM_ID ASC;
