-- 프로그래머스 131534번. 상품을 구매한 회원 비율 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131534

WITH USER_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),

USER_PURCHASE_INFO AS (
    SELECT DISTINCT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM USER_2021)
),

PURCHASE_INFO AS (
    SELECT YEAR, MONTH, COUNT(USER_ID) AS PURCHASED_USERS
    FROM USER_PURCHASE_INFO
    GROUP BY YEAR, MONTH
)

SELECT YEAR, MONTH, PURCHASED_USERS, ROUND(PURCHASED_USERS / (SELECT COUNT(*) FROM USER_2021), 1) AS PUCHASED_RATIO
FROM PURCHASE_INFO
ORDER BY YEAR, MONTH;
