-- 프로그래머스 301651번. 멸종위기의 대장균 찾기
-- https://school.programmers.co.kr/learn/courses/30/lessons/301651

-- 대장균의 세대를 저장하는 테이블
WITH RECURSIVE ECOLI_GENERATION AS (
    -- 초기 세대
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 다음 세대 (재귀)
    SELECT A.ID, A.PARENT_ID, B.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA A
    JOIN ECOLI_GENERATION B
    ON A.PARENT_ID = B.ID
),

-- 자식이 없는 대장균을 저장하는 테이블
ECOLI_LEAF AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI_GENERATION
WHERE ID IN (SELECT ID FROM ECOLI_LEAF)
GROUP BY GENERATION
ORDER BY GENERATION ASC
