-- 프로그래머스 144856번. 저자 별 카테고리 별 매출액 집계하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/144856

WITH BOOK_SALES_DATA AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
),

BOOK_INFO AS (
    SELECT A.BOOK_ID, A.CATEGORY, A.AUTHOR_ID, A.PRICE * B.SALES AS SALES
    FROM BOOK AS A
    JOIN BOOK_SALES_DATA AS B
    ON A.BOOK_ID = B.BOOK_ID
),

AUTHOR_CATEGORY_SALES_INFO AS (
    SELECT AUTHOR_ID, CATEGORY, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_INFO
    GROUP BY AUTHOR_ID, CATEGORY
)

SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, A.TOTAL_SALES
FROM AUTHOR_CATEGORY_SALES_INFO AS A
JOIN AUTHOR AS B
ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC;
