-- 프로그래머스 276036번. 언어별 개발자 분류하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/276036


WITH PYTHON_DEVELOPERS AS (
    SELECT *
    FROM DEVELOPERS
    WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0
),

FRONTEND_DEVELOPERS AS (
    SELECT *
    FROM DEVELOPERS AS D
    JOIN SKILLCODES AS S
    ON D.SKILL_CODE & S.CODE > 0
    WHERE S.CATEGORY = 'Front End'
),

C_DEVELOPER AS (
    SELECT *
    FROM DEVELOPERS
    WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0
)

SELECT DISTINCT
    CASE
        WHEN D.ID IN (SELECT ID FROM PYTHON_DEVELOPERS) AND D.ID IN (SELECT ID FROM FRONTEND_DEVELOPERS) THEN 'A'
        WHEN D.ID IN (SELECT ID FROM C_DEVELOPER) THEN 'B'
        WHEN D.ID IN (SELECT ID FROM FRONTEND_DEVELOPERS) THEN 'C'
        ELSE NULL
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS AS D
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;
