-- 프로그래머스 151141번. 자동차 대여 기록 별 대여 금액 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/151141

WITH TRUCK_RENTAL_HISTORY AS (
    SELECT A.HISTORY_ID, DATEDIFF(A.END_DATE, A.START_DATE) + 1 AS RENTAL_DURATION, B.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
    JOIN CAR_RENTAL_COMPANY_CAR AS B
    ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = '트럭'
),

TRUCK_DISCOUNT_PLAN AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)

SELECT
    HISTORY_ID,
    CASE
        WHEN RENTAL_DURATION >= 90 THEN ROUND(DAILY_FEE * RENTAL_DURATION * (100 - (SELECT DISCOUNT_RATE FROM TRUCK_DISCOUNT_PLAN WHERE DURATION_TYPE = '90일 이상')) / 100, 0)
        WHEN RENTAL_DURATION >= 30 THEN ROUND(DAILY_FEE * RENTAL_DURATION * (100 - (SELECT DISCOUNT_RATE FROM TRUCK_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상')) / 100, 0)
        WHEN RENTAL_DURATION >= 7 THEN ROUND(DAILY_FEE * RENTAL_DURATION * (100 - (SELECT DISCOUNT_RATE FROM TRUCK_DISCOUNT_PLAN WHERE DURATION_TYPE = '7일 이상')) / 100, 0)
        ELSE DAILY_FEE * RENTAL_DURATION
    END AS FEE
FROM TRUCK_RENTAL_HISTORY
ORDER BY FEE DESC, HISTORY_ID DESC
