-- 프로그래머스 131537번. 오프라인/온라인 판매 데이터 통합하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131537

WITH ONLINE_MARCH_SALES AS (
    SELECT
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
),

OFFLINE_MARCH_SALES AS (
    SELECT
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
        PRODUCT_ID,
        NULL AS USER_ID,
        SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
)

SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_MARCH_SALES
UNION ALL
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM OFFLINE_MARCH_SALES
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
