-- 프로그래머스 62284번. 우유와 요거트가 담긴 장바구니
-- https://school.programmers.co.kr/learn/courses/30/lessons/62284

WITH YOGURT_CART AS (
    SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt'
),

MILK_CART AS (
    SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk'
)

SELECT DISTINCT CART_ID
FROM YOGURT_CART
WHERE CART_ID IN (SELECT CART_ID FROM MILK_CART)
ORDER BY CART_ID;
