-- 프로그래머스 133027번. 주문량이 많은 아이스크림들 조회하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/133027

WITH ORDER_LIST AS (
    SELECT FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
    UNION ALL
    SELECT FLAVOR, TOTAL_ORDER
    FROM JULY
),

ORDER_DATA AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM ORDER_LIST
    GROUP BY FLAVOR
)

SELECT FLAVOR
FROM ORDER_DATA
ORDER BY TOTAL_ORDER DESC
LIMIT 3;
