-- 프로그래머스 131118번. 서울에 위치한 식당 목록 출력하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131118

SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, B.SCORE
FROM REST_INFO AS A
JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) AS B
ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY B.SCORE DESC, A.FAVORITES DESC;
