-- 프로그래머스 131532번. 년, 월, 성별 별 상품 구매 회원 수 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131532

WITH ONLINE_SALE_INFO AS (
    SELECT DISTINCT A.USER_ID, YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, B.GENDER
    FROM ONLINE_SALE AS A
    JOIN USER_INFO AS B
    ON A.USER_ID = B.USER_ID
    WHERE B.GENDER IS NOT NULL
)

SELECT YEAR, MONTH, GENDER, COUNT(*) AS USERS
FROM ONLINE_SALE_INFO
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;
