-- 프로그래머스 151139번. 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/151139

SELECT MONTH (START_DATE) AS MONTH, CAR_ID, COUNT (*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH (START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT (*) >= 5
) AND MONTH (START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;
