-- 프로그래머스 164668번. 조건에 맞는 사용자와 총 거래금액 조회하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/164668

SELECT A.USER_ID, A.NICKNAME, B.TOTAL_PRICE
FROM USED_GOODS_USER AS A
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_PRICE >= 700000
) AS B
ON A.USER_ID = B.WRITER_ID
ORDER BY B.TOTAL_PRICE ASC;
