-- 프로그래머스 273712번. 업그레이드 할 수 없는 아이템 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/273712

WITH UNUPGRADABLE_ITEMS AS (
    SELECT DISTINCT ITEM_ID
    FROM ITEM_TREE
    WHERE ITEM_ID NOT IN (
        SELECT PARENT_ITEM_ID
        FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IS NOT NULL
    )
)

SELECT DISTINCT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
JOIN UNUPGRADABLE_ITEMS AS U
ON I.ITEM_ID = U.ITEM_ID
ORDER BY ITEM_ID DESC
