-- 프로그래머스 144855번. 카테고리 별 도서 판매량 집계하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/144855

SELECT B.CATEGORY, SUM(A.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS A
JOIN BOOK AS B
ON A.BOOK_ID = B.BOOK_ID
WHERE YEAR (SALES_DATE) = 2022 AND MONTH (SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;
