-- 프로그래머스 293261번. 물고기 종류 별 대어 찾기
-- https://school.programmers.co.kr/learn/courses/30/lessons/293261

SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE (A.FISH_TYPE, A.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO AS A
    GROUP BY FISH_TYPE
)
ORDER BY A.ID ASC;
